#!/bin/sh
# new-profile.sh — scaffold a new stack profile so an unsupported stack is a guided,
# validated workflow (START-HERE.md §2B; the kit is never limited to pre-written stacks).
# Usage: sh scripts/new-profile.sh <stack-name>
# Creates profiles/<stack>.md (from _TEMPLATE.md) + profiles/<stack>/{ci.yml,CODEOWNERS,BRANCH-PROTECTION.md}.
# The stub ci.yml declares all 8 gate-* ids (placeholder run commands) so it passes the
# STRUCTURAL ci-gates.sh check immediately. Fill the 11 sections + real commands, then run
# `sh conformance/profile-completeness.sh` to validate.
set -eu

STACK="${1:-}"
[ -n "$STACK" ] || { echo "usage: new-profile.sh <stack-name>" >&2; exit 2; }
case "$STACK" in
  */*|*" "*|.*) echo "error: stack name must be a simple slug (e.g. go, dotnet, swift)" >&2; exit 2 ;;
esac
[ -f profiles/_TEMPLATE.md ] || { echo "error: run from the kit repo root (profiles/_TEMPLATE.md not found)" >&2; exit 1; }
if [ -e "profiles/${STACK}.md" ] || [ -e "profiles/${STACK}" ]; then
  echo "error: profiles/${STACK}.md or profiles/${STACK}/ already exists — choose another name" >&2; exit 1
fi

esc() { printf '%s' "$1" | sed 's/[&/\\]/\\&/g'; }

# 1. profile.md from the template (title stamped; sections remain [...] to fill)
cp profiles/_TEMPLATE.md "profiles/${STACK}.md"
sed -i.bak "s/\[Stack Name\]/$(esc "$STACK")/" "profiles/${STACK}.md" && rm -f "profiles/${STACK}.md.bak"

# 2. companion dir + stub ci.yml declaring all 8 required gate ids
mkdir -p "profiles/${STACK}"
cat > "profiles/${STACK}/ci.yml" <<'YAML'
# Reference CI pipeline — STUB generated by scripts/new-profile.sh.
# Replace each `run:` TODO with your stack's command. The 8 gate-* ids below satisfy
# DEVELOPMENT-STANDARDS.md §14 and conformance/ci-gates.sh — do NOT rename them.
name: CI
on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read
  id-token: write
  attestations: write
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # TODO: add your language/runtime setup action
      - name: Lint
        id: gate-lint
        run: echo "TODO: lint command"
      - name: Type-check
        id: gate-type-check
        run: echo "TODO: type-check / compile command"
      - name: Test + coverage (>=80%)
        id: gate-test
        run: echo "TODO: test + coverage command"
      - name: Build
        id: gate-build
        run: echo "TODO: build command"
      - name: Secret scan
        id: gate-secret-scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Dependency vulnerability scan
        id: gate-dep-scan
        run: echo "TODO: dependency vulnerability scan command"
      - name: Generate SBOM (CycloneDX)
        id: gate-sbom
        run: echo "TODO: SBOM generation command"
      - name: Attest build provenance
        id: gate-provenance
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: dist/**   # TODO: your built artifact path
YAML

# 3. governance companions (derive from the shipped Python reference; stack-neutral)
sed "s/Python profile/${STACK} profile/" profiles/python/CODEOWNERS > "profiles/${STACK}/CODEOWNERS"
sed "s/(Python profile)/(${STACK} profile)/" profiles/python/BRANCH-PROTECTION.md > "profiles/${STACK}/BRANCH-PROTECTION.md"

cat <<EOF
Scaffolded:
  profiles/${STACK}.md
  profiles/${STACK}/ci.yml          (stub — passes ci-gates structurally)
  profiles/${STACK}/CODEOWNERS
  profiles/${STACK}/BRANCH-PROTECTION.md

Next:
  1. Fill all 11 sections in profiles/${STACK}.md (replace every [...]).
  2. Replace each TODO 'run:' in profiles/${STACK}/ci.yml with your stack's real command.
  3. Validate:  sh conformance/profile-completeness.sh
  4. Record the choice as ADR-000 and select this profile at Inception.
EOF
