#!/bin/sh
# new-profile.sh — scaffold a new stack profile so an unsupported stack is a guided,
# validated workflow (START-HERE.md §2B; the kit is never limited to pre-written stacks).
# Usage: sh scripts/new-profile.sh <stack-name>
# Creates profiles/<stack>.md (from _TEMPLATE.md) + profiles/<stack>/{ci.yml,CODEOWNERS,BRANCH-PROTECTION.md}.
# The stub ci.yml is CONFORMANT on creation: SHA-pinned actions, a checksum-verified gitleaks binary,
# and a separate visibility-gated provenance job (passes action-pinning.sh + provenance-precondition.sh
# + ci-gates.sh). Companions are emitted INLINE (no cross-profile dependency), so generation works in
# any --profile export. Fill the 11 sections + the TODO run commands, then run
# `sh conformance/profile-completeness.sh` to validate.
set -eu

STACK="${1:-}"
[ -n "$STACK" ] || { echo "usage: new-profile.sh <stack-name>" >&2; exit 2; }
case "$STACK" in
  *[!a-z0-9._-]*|.*|-*) echo "error: stack name must be a simple slug — lowercase a-z, 0-9, '.', '_', '-', not starting with '.' or '-' (e.g. go, dotnet, java-spring)" >&2; exit 2 ;;
esac
[ -f profiles/_TEMPLATE.md ] || { echo "error: run from the kit repo root (profiles/_TEMPLATE.md not found)" >&2; exit 1; }
if [ -e "profiles/${STACK}.md" ] || [ -e "profiles/${STACK}" ]; then
  echo "error: profiles/${STACK}.md or profiles/${STACK}/ already exists — choose another name" >&2; exit 1
fi

# Clean up a partial scaffold if any step below fails (so a failed run never strands a
# half-built profile that then blocks retries via the existence guard above).
cleanup() { [ "${OK:-0}" = 1 ] || rm -rf "profiles/${STACK}.md" "profiles/${STACK}"; }
trap cleanup EXIT

esc() { printf '%s' "$1" | sed 's/[&/\\]/\\&/g'; }

# 1. profile.md from the template (title stamped; sections remain [...] to fill)
cp profiles/_TEMPLATE.md "profiles/${STACK}.md"
sed -i.bak "s/\[Stack Name\]/$(esc "$STACK")/" "profiles/${STACK}.md" && rm -f "profiles/${STACK}.md.bak"

# 2. companion dir + CONFORMANT stub ci.yml (pinned actions, gated provenance job)
mkdir -p "profiles/${STACK}"
cat > "profiles/${STACK}/ci.yml" <<'YAML'
# Reference CI pipeline — STUB generated by scripts/new-profile.sh.
# CONFORMANT on creation: SHA-pinned actions, a checksum-verified gitleaks binary, and a separate
# visibility-gated provenance job. Replace each `run:` TODO with your stack's command; do NOT rename
# the gate-* ids (conformance/ci-gates.sh + DEVELOPMENT-STANDARDS.md §14 assert them), keep every
# `uses:` SHA-pinned (action-pinning.sh scopes to the typescript-node reference only — keep pins yourself; generator-golden-path mirrors the inline check), and keep the provenance job visibility-gated
# (conformance/provenance-precondition.sh).
name: CI
on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read
jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          fetch-depth: 0   # full history so the secret scan sees all commits
      # TODO: add your language/runtime setup action (SHA-pin it, e.g. actions/setup-go@<sha>  # vX)
      - name: Lint
        id: gate-lint
        run: |
          echo "TODO: lint command"
      - name: Type-check
        id: gate-type-check
        run: |
          echo "TODO: type-check / compile command"
      - name: Test + coverage (>=80%)
        id: gate-test
        run: |
          echo "TODO: test + coverage command"
      - name: Build
        id: gate-build
        run: |
          echo "TODO: build command"
      - name: Secret scan
        id: gate-secret-scan
        # Range-independent full-tree scan via the pinned, checksum-verified gitleaks binary
        # (H4b supply-chain pattern; language-agnostic). Avoids gitleaks-action's PR merge-ref
        # failure mode and needs only contents:read.
        run: |
          GL_VER=8.24.3
          curl -sSfL "https://github.com/gitleaks/gitleaks/releases/download/v${GL_VER}/gitleaks_${GL_VER}_linux_x64.tar.gz" -o /tmp/gitleaks.tgz
          echo "9991e0b2903da4c8f6122b5c3186448b927a5da4deef1fe45271c3793f4ee29c  /tmp/gitleaks.tgz" | sha256sum -c -
          tar -xzf /tmp/gitleaks.tgz -C /tmp gitleaks
          /tmp/gitleaks dir . --no-banner --redact
      - name: Dependency vulnerability scan
        id: gate-dep-scan
        run: |
          echo "TODO: dependency vulnerability scan (TS reference uses 'npm audit --omit=dev --audit-level=high'; python: 'pip-audit')"
      - name: Generate SBOM (CycloneDX)
        id: gate-sbom
        # TODO: SBOM generation. See profiles/typescript-node/ci.yml for a worked example
        # ('npx @cyclonedx/cyclonedx-npm …'). Python footgun: cyclonedx-py ships in 'cyclonedx-bom',
        # so use 'uvx --from cyclonedx-bom cyclonedx-py … --output-file sbom.json'.
        run: |
          echo "TODO: SBOM generation command"
      - name: Upload build artifact (for provenance)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4
        with:
          name: build-artifact
          path: dist/**          # TODO: your built artifact path
          if-no-files-found: error

  # NOTE (provenance precondition): the SLSA attestations API is unavailable on user-owned PRIVATE
  # repos, so this job is gated to run only on public or org-owned repos — otherwise `main` would go
  # red on first merge with no in-repo explanation. Make the repo public or move it to a GitHub org.
  provenance:
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && (github.event.repository.private == false || github.event.repository.owner.type == 'Organization')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write       # scoped to this push-only job (build-provenance attestation)
      attestations: write
    steps:
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093  # v4
        with:
          name: build-artifact
          path: build-artifact
      - name: Attest build provenance
        id: gate-provenance
        uses: actions/attest-build-provenance@ef244123eb79f2f7a7e75d99086184180e6d0018  # v1
        with:
          subject-path: build-artifact/**
YAML

# 3. governance companions — emitted INLINE (no cross-profile dependency, so generation works in any
#    --profile export, e.g. one that pruned profiles/typescript-node/). COPY & ADAPT placeholders.
cat > "profiles/${STACK}/CODEOWNERS" <<'EOF'
# Reference CODEOWNERS — copy & adapt for this stack profile.
# COPY & ADAPT: copy to .github/CODEOWNERS (or repo root). Routes review so the
# builder is never the sole reviewer/merger (DEVELOPMENT-PROCESS.md §2, §12).
# Replace @your-org/* with real teams.

*            @your-org/engineering
/.github/    @your-org/platform
/profiles/   @your-org/platform
EOF

cat > "profiles/${STACK}/BRANCH-PROTECTION.md" <<'EOF'
# Branch Protection — reference setup (copy & adapt for this stack profile)

Enforces the §14 contract at the repo boundary: `main` protected, green CI to merge, builder ≠ sole merger. COPY & ADAPT — replace `OWNER/REPO` and team handles.

## What to require
- The CI status check (`ci`) must pass before merge.
- At least 1 approving review from someone other than the author.
- Stale approvals dismissed on new commits.
- Branch up to date before merge.
- (Org/plan-dependent) CODEOWNERS review required; self-merge disallowed.

## Apply via GitHub CLI
Run **after** the CI workflow has run at least once (so the check name `ci` is registered):

```bash
gh api -X PUT repos/OWNER/REPO/branches/main/protection --input - <<'JSON'
{
  "required_status_checks": { "strict": true, "contexts": ["ci"] },
  "enforce_admins": true,
  "required_pull_request_reviews": {
    "required_approving_review_count": 1,
    "dismiss_stale_reviews": true,
    "require_code_owner_reviews": true
  },
  "restrictions": null
}
JSON
```

> "Builder ≠ sole merger" is enforced by required reviews + CODEOWNERS. GitHub cannot strictly forbid every user from merging their own PR on all plans; on GitHub Enterprise use rulesets / required reviewers. Document the policy in the project `CLAUDE.md` regardless.

> **Solo scale:** set `"enforce_admins": false` so the owner can admin-merge their own PR (`gh pr merge --admin`) — the audit-trailed self-ratification of `START-HERE.md`'s solo/lite track. Flip it back to `true` the moment a second reviewer exists, so the required-review rule then enforces real review.
EOF

OK=1   # all files created; the EXIT trap will keep them

cat <<EOF
Scaffolded:
  profiles/${STACK}.md
  profiles/${STACK}/ci.yml          (conformant stub — pinned actions, gated provenance, passes ci-gates)
  profiles/${STACK}/CODEOWNERS
  profiles/${STACK}/BRANCH-PROTECTION.md

Next:
  1. Fill all 11 sections in profiles/${STACK}.md (replace every [...]).
  2. Replace each TODO 'run:' in profiles/${STACK}/ci.yml with your stack's real command
     (keep the gate-* ids, keep every uses: SHA-pinned, keep the provenance job visibility-gated).
  3. Validate:  sh conformance/profile-completeness.sh
  4. Record the choice as ADR-000 and select this profile at Inception.
EOF
